openapi: 3.0.0
info:
  title: Todo API - Notifications
  version: 1.0.0
  description: Notifications API for Branch 012 features

paths:
  /{user_id}/notifications:
    get:
      summary: List notifications
      description: Retrieve all notifications for a user, optionally filtered by read status
      tags:
        - Notifications
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: User ID for scoping
        - name: unread_only
          in: query
          required: false
          schema:
            type: boolean
            default: false
          description: If true, only return unread notifications
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
            minimum: 1
            maximum: 100
          description: Maximum number of notifications to return
      responses:
        '200':
          description: List of notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '401':
          description: Unauthorized
        '404':
          description: User not found

  /{user_id}/notifications/{id}/read:
    patch:
      summary: Mark notification as read
      description: Mark a single notification as read
      tags:
        - Notifications
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Notification ID
      responses:
        '200':
          description: Notification marked as read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '401':
          description: Unauthorized
        '404':
          description: Notification not found

  /{user_id}/notifications/read-all:
    patch:
      summary: Mark all notifications as read
      description: Mark all unread notifications for a user as read
      tags:
        - Notifications
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: All notifications marked as read
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: Number of notifications marked as read
        '401':
          description: Unauthorized

components:
  schemas:
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
        message:
          type: string
        taskId:
          type: string
          format: uuid
          nullable: true
        read:
          type: boolean
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - userId
        - message
        - read
        - createdAt
