apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reminder-check-cron
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 1m"
  - name: direction
    value: "input"
