# Redis State Store for Dapr
# Used for idempotency checking - prevents duplicate event processing
# Services that don't need statestore use no-statestore config

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  # Enable key-based access pattern
  - name: keyPrefix
    value: none
