# Dapr Subscriptions for Audit Service
# Subscribes to all task events for complete audit trail

apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: audit-service-task-created
spec:
  topic: task-created
  routes:
    default: /events/task-created
  pubsubname: pubsub
  scopes:
    - audit-service

---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: audit-service-task-updated
spec:
  topic: task-updated
  routes:
    default: /events/task-updated
  pubsubname: pubsub
  scopes:
    - audit-service

---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: audit-service-task-completed
spec:
  topic: task-completed
  routes:
    default: /events/task-completed
  pubsubname: pubsub
  scopes:
    - audit-service

---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: audit-service-task-deleted
spec:
  topic: task-deleted
  routes:
    default: /events/task-deleted
  pubsubname: pubsub
  scopes:
    - audit-service
