# Dapr Subscriptions for WebSocket Service
# Subscribes to all task update events to broadcast to connected clients

apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: websocket-service-task-created
spec:
  topic: task-created
  routes:
    default: /events/task-updates
  pubsubname: pubsub
  scopes:
    - websocket-service

---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: websocket-service-task-updated
spec:
  topic: task-updated
  routes:
    default: /events/task-updates
  pubsubname: pubsub
  scopes:
    - websocket-service

---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: websocket-service-task-completed
spec:
  topic: task-completed
  routes:
    default: /events/task-updates
  pubsubname: pubsub
  scopes:
    - websocket-service

---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: websocket-service-task-deleted
spec:
  topic: task-deleted
  routes:
    default: /events/task-updates
  pubsubname: pubsub
  scopes:
    - websocket-service
